console.log("");
console.log("RabbitMQ Manager v" + require('../package.json').version);
console.log("");
console.log("Usage: rabbit [command] [args]");
console.log("");
console.log("Commands:");
console.log("");
console.log("   config         displays a given configuration file");
console.log("   export         exports the current config to a specified file");
console.log("   help           displays this message");
console.log("   import         import a given file or JSON string to the config");
console.log("   query          carries out a generic query against the API");
console.log("   set            add a new configuration entry");
console.log("   unset          remove a configuration entry");
console.log("   version        displays the version of RabbitMQ Manager");
console.log("");